name: CI
on:
  workflow_dispatch:
    branches:
    - master
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
  # In this phase, the code is pulled from master and the site rendered in Hugo. The built site is stored as an artifact for other stages.
    runs-on: ubuntu-latest
    steps:
    # Check out master branch from the repo.
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
        ref: master
    # Ensure the site succeeds Hugo builds. If it fails for some reason, the pipeline will halt.
    - name: Build site with Hugo
      run: hugo -D
